# encoding: UTF-8

require 'spec_helper'
require 'normatron/filters/keep_filter'

describe Normatron::Filters::KeepFilter do
  it_should_behave_like "string processor"
  it_should_behave_like "character cleaner", :keep, [:Graph]
  it_should_behave_like "character cleaner", :keep, [:Punct]
  it_should_behave_like "character cleaner", :keep, [:Upper]
  it_should_behave_like "character cleaner", :keep, [:Word]
  it_should_behave_like "character cleaner", :keep, [:Latin]
  it_should_behave_like "character cleaner", :keep, [:L]
  it_should_behave_like "character cleaner", :keep, [:M]
  it_should_behave_like "character cleaner", :keep, [:N]
  it_should_behave_like "character cleaner", :keep, [:P]
  it_should_behave_like "character cleaner", :keep, [:S]
  it_should_behave_like "character cleaner", :keep, [:Z]
  it_should_behave_like "character cleaner", :keep, [:C]
  it_should_behave_like "character cleaner", :keep, [:Graph, :Punct]
  it_should_behave_like "character cleaner", :keep, [:Graph, :Upper]
  it_should_behave_like "character cleaner", :keep, [:Graph, :Word]
  it_should_behave_like "character cleaner", :keep, [:Graph, :Latin]
  it_should_behave_like "character cleaner", :keep, [:Graph, :L]
  it_should_behave_like "character cleaner", :keep, [:Graph, :M]
  it_should_behave_like "character cleaner", :keep, [:Graph, :N]
  it_should_behave_like "character cleaner", :keep, [:Graph, :P]
  it_should_behave_like "character cleaner", :keep, [:Graph, :S]
  it_should_behave_like "character cleaner", :keep, [:Graph, :Z]
  it_should_behave_like "character cleaner", :keep, [:Graph, :C]
  it_should_behave_like "character cleaner", :keep, [:Punct, :Upper]
  it_should_behave_like "character cleaner", :keep, [:Punct, :Word]
  it_should_behave_like "character cleaner", :keep, [:Punct, :Latin]
  it_should_behave_like "character cleaner", :keep, [:Punct, :L]
  it_should_behave_like "character cleaner", :keep, [:Punct, :M]
  it_should_behave_like "character cleaner", :keep, [:Punct, :N]
  it_should_behave_like "character cleaner", :keep, [:Punct, :P]
  it_should_behave_like "character cleaner", :keep, [:Punct, :S]
  it_should_behave_like "character cleaner", :keep, [:Punct, :Z]
  it_should_behave_like "character cleaner", :keep, [:Punct, :C]
  it_should_behave_like "character cleaner", :keep, [:Upper, :Word]
  it_should_behave_like "character cleaner", :keep, [:Upper, :Latin]
  it_should_behave_like "character cleaner", :keep, [:Upper, :L]
  it_should_behave_like "character cleaner", :keep, [:Upper, :M]
  it_should_behave_like "character cleaner", :keep, [:Upper, :N]
  it_should_behave_like "character cleaner", :keep, [:Upper, :P]
  it_should_behave_like "character cleaner", :keep, [:Upper, :S]
  it_should_behave_like "character cleaner", :keep, [:Upper, :Z]
  it_should_behave_like "character cleaner", :keep, [:Upper, :C]
  it_should_behave_like "character cleaner", :keep, [:Word, :Latin]
  it_should_behave_like "character cleaner", :keep, [:Word, :L]
  it_should_behave_like "character cleaner", :keep, [:Word, :M]
  it_should_behave_like "character cleaner", :keep, [:Word, :N]
  it_should_behave_like "character cleaner", :keep, [:Word, :P]
  it_should_behave_like "character cleaner", :keep, [:Word, :S]
  it_should_behave_like "character cleaner", :keep, [:Word, :Z]
  it_should_behave_like "character cleaner", :keep, [:Word, :C]
  it_should_behave_like "character cleaner", :keep, [:Latin, :L]
  it_should_behave_like "character cleaner", :keep, [:Latin, :M]
  it_should_behave_like "character cleaner", :keep, [:Latin, :N]
  it_should_behave_like "character cleaner", :keep, [:Latin, :P]
  it_should_behave_like "character cleaner", :keep, [:Latin, :S]
  it_should_behave_like "character cleaner", :keep, [:Latin, :Z]
  it_should_behave_like "character cleaner", :keep, [:Latin, :C]
  it_should_behave_like "character cleaner", :keep, [:L, :M]
  it_should_behave_like "character cleaner", :keep, [:L, :N]
  it_should_behave_like "character cleaner", :keep, [:L, :P]
  it_should_behave_like "character cleaner", :keep, [:L, :S]
  it_should_behave_like "character cleaner", :keep, [:L, :Z]
  it_should_behave_like "character cleaner", :keep, [:L, :C]
  it_should_behave_like "character cleaner", :keep, [:M, :N]
  it_should_behave_like "character cleaner", :keep, [:M, :P]
  it_should_behave_like "character cleaner", :keep, [:M, :S]
  it_should_behave_like "character cleaner", :keep, [:M, :Z]
  it_should_behave_like "character cleaner", :keep, [:M, :C]
  it_should_behave_like "character cleaner", :keep, [:N, :P]
  it_should_behave_like "character cleaner", :keep, [:N, :S]
  it_should_behave_like "character cleaner", :keep, [:N, :Z]
  it_should_behave_like "character cleaner", :keep, [:N, :C]
  it_should_behave_like "character cleaner", :keep, [:P, :S]
  it_should_behave_like "character cleaner", :keep, [:P, :Z]
  it_should_behave_like "character cleaner", :keep, [:P, :C]
  it_should_behave_like "character cleaner", :keep, [:S, :Z]
  it_should_behave_like "character cleaner", :keep, [:S, :C]
  it_should_behave_like "character cleaner", :keep, [:Z, :C]
end